name: "delete-stale-branch"
on:
  pull_request:
    branches: [main]
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CICD_GITHUB_REPOSITORY_TOKEN }}
